name: EhBans
main: com.ehaqui.EhBans.EhBans
version: 0.6.7
author: Lucas Didur
description: Manage Bans With SourceBans
website: http://ehaqui.com
commands:
    ehbans:
        description: 'Show main menu'
        usage: '/ehaway <comandos>'
        aliases: [ebans]
    fban:
        description: 'Bans a specified player from the server.'
        usage: '/fban <reason>'
    ban:
        description: 'Bans a specified player from the server.'
        usage: '/ban [player] <time> <reason>'
    unban:
        description: 'Bans a specified player from the server.'
        usage: '/unban [player] [reason]'
    kick:
        description: 'Bans a specified player from the server.'
        usage: '/kick [player]'